development:
  adapter: postgresql
  encoding: unicode
  database: EWManagement_development
  pool: 5
  username: Noah_AT
  password:
      
test:
  adapter: postgresql
  encoding: unicode
  database: EWManagement_test
  pool: 5
  username: Noah_AT
  password: